# Generated by Django 3.2 on 2021-05-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=45)),
                ('prioridade', models.CharField(max_length=30)),
                ('chamado_titulo', models.CharField(max_length=30)),
                ('chamado_tipo', models.CharField(max_length=30)),
                ('chamado_corpo', models.TextField()),
                ('data_hora_abertura', models.DateTimeField()),
            ],
        ),
    ]
