# Generated by Django 3.2 on 2021-05-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helpdesk_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamado',
            old_name='corpo',
            new_name='descricao',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(max_length=120),
        ),
    ]
