# Generated by Django 3.2 on 2021-05-01 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Helpdesk_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chamados',
            new_name='Chamado',
        ),
    ]
