# Generated by Django 3.2 on 2021-05-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helpdesk_app', '0002_rename_chamados_chamado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamado',
            old_name='chamado_tipo',
            new_name='chamado_topico',
        ),
        migrations.AddField(
            model_name='chamado',
            name='status_chamado',
            field=models.CharField(default='aberto', max_length=30),
            preserve_default=False,
        ),
    ]
