# Generated by Django 3.2 on 2021-06-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helpdesk_app', '0002_auto_20210529_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='agente_atribuido',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_atendente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='autor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='topico',
            field=models.CharField(max_length=50),
        ),
    ]
