# Generated by Django 3.2 on 2021-06-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Helpdesk_app', '0003_auto_20210601_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamado',
            old_name='data_hora_abertura',
            new_name='hora_abertura',
        ),
    ]
