# Generated by Django 3.2 on 2021-05-02 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Helpdesk_app', '0003_auto_20210501_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamado',
            old_name='chamado_corpo',
            new_name='corpo',
        ),
        migrations.RenameField(
            model_name='chamado',
            old_name='chamado_titulo',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='chamado',
            old_name='chamado_topico',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='chamado',
            old_name='status_chamado',
            new_name='topico',
        ),
    ]
