# Generated by Django 3.2 on 2021-06-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helpdesk_app', '0004_rename_data_hora_abertura_chamado_hora_abertura'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='is_lido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chamado',
            name='local_afetado',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='hora_abertura',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='prioridade',
            field=models.CharField(choices=[('muito_alta', 'Muito Alta'), ('media', 'Media'), ('baixa', 'Baixa')], max_length=30),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('resolvido', 'Resolvido'), ('pendente', 'Pendente'), ('fechado', 'Fechado'), ('excluido', 'Excluido')], max_length=30),
        ),
    ]
