# Generated by Django 3.2 on 2021-05-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Helpdesk_app', '0005_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=50)),
                ('nome_completo', models.CharField(max_length=60)),
                ('senha_usuario', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=45)),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
