# Generated by Django 3.2 on 2021-05-17 13:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Helpdesk_app', '0006_auto_20210514_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
