# Generated by Django 3.2 on 2021-06-04 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Helpdesk_app', '0007_alter_chamado_agente_atribuido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chamado',
            old_name='is_lido',
            new_name='foi_lido',
        ),
    ]
