# Generated by Django 3.2.4 on 2021-06-23 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Helpdesk_app', '0012_alter_anexo_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='anexos',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Helpdesk_app.anexo'),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='arquivo',
            field=models.FileField(upload_to=''),
        ),
    ]
