# Generated by Django 3.2.4 on 2021-06-23 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Helpdesk_app', '0013_auto_20210623_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='anexos',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Helpdesk_app.anexo'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='anexo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Helpdesk_app.anexo'),
        ),
    ]
