# Generated by Django 3.2.4 on 2021-06-29 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Helpdesk_app', '0015_rename_anexos_chamado_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='anexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Helpdesk_app.anexo'),
        ),
    ]
