# Generated by Django 3.2.4 on 2021-07-01 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Helpdesk_app', '0016_alter_mensagem_anexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='anexo',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='anexo',
        ),
        migrations.CreateModel(
            name='Anexos_chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Helpdesk_app.anexo')),
                ('chamado', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Helpdesk_app.chamado')),
            ],
        ),
    ]
