# Generated by Django 3.2 on 2021-07-25 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Helpdesk_app', '0017_auto_20210701_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_Empresa', models.CharField(max_length=50)),
                ('Nome_Sistema', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='anexos_chamado',
            name='anexo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Helpdesk_app.anexo'),
        ),
    ]
